// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.0
// source: database.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerDataType int32

const (
	PlayerDataType_BASE PlayerDataType = 0
	PlayerDataType_BAG  PlayerDataType = 1
)

// Enum value maps for PlayerDataType.
var (
	PlayerDataType_name = map[int32]string{
		0: "BASE",
		1: "BAG",
	}
	PlayerDataType_value = map[string]int32{
		"BASE": 0,
		"BAG":  1,
	}
)

func (x PlayerDataType) Enum() *PlayerDataType {
	p := new(PlayerDataType)
	*p = x
	return p
}

func (x PlayerDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_database_proto_enumTypes[0].Descriptor()
}

func (PlayerDataType) Type() protoreflect.EnumType {
	return &file_database_proto_enumTypes[0]
}

func (x PlayerDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerDataType.Descriptor instead.
func (PlayerDataType) EnumDescriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{0}
}

// @dbtool:string|myplay|session:Uid@uint64|#玩家会话信息
type SessionData struct {
	state         protoimpl.MessageState `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`

	Uid       uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                // 用户ID
	Name      string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 昵称
	LoginTime int64    `protobuf:"varint,4,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`   // 创建时间
	LoginIp   string   `protobuf:"bytes,5,opt,name=login_ip,json=loginIp,proto3" json:"login_ip,omitempty"`          // 客户端IP
	Version   string   `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`                         // 版本
	DeviceId  string   `protobuf:"bytes,7,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // 设备id
	Platform  Platform `protobuf:"varint,8,opt,name=platform,proto3,enum=myplay.Platform" json:"platform,omitempty"` // 登录平台
}

func (x *SessionData) Reset() {
	*x = SessionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionData) ProtoMessage() {}

func (x *SessionData) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionData.ProtoReflect.Descriptor instead.
func (*SessionData) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{0}
}

func (x *SessionData) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SessionData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionData) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

func (x *SessionData) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *SessionData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SessionData) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SessionData) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PlatformTypeNone
}

// 玩家账号数据
type AccountData struct {
	state         protoimpl.MessageState `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`

	Id         int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" xorm:"bigint autoincr pk comment('数据库唯一id')"`                                                       // @inject_tag: xorm:"bigint autoincr pk comment('数据库唯一id')"
	Uid        uint64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty" xorm:"bigint index notnull comment('玩家uid')"`                                                     // @inject_tag: xorm:"bigint index notnull comment('玩家uid')"
	Name       string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" xorm:"varchar(25) index comment('用户名')"`                                                    // @inject_tag: xorm:"varchar(25) index comment('用户名')"
	Email      string    `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty" xorm:"varchar(50) index comment('邮箱')"`                                                  // @inject_tag: xorm:"varchar(50) index comment('邮箱')"
	Phone      string    `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty" xorm:"varchar(16) index comment('手机号')"`                                                  // @inject_tag: xorm:"varchar(16) index comment('手机号')"
	Password   string    `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty" xorm:"varbinary(255) comment('密码hash值')"`                                            // @inject_tag: xorm:"varbinary(255) comment('密码hash值')"
	SecretKey  string    `protobuf:"bytes,7,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty" xorm:"varbinary(32) comment('密码随机密钥')"`                         // @inject_tag: xorm:"varbinary(32) comment('密码随机密钥')"
	CreateTime int64     `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" xorm:"bigint comment('创建时间')"`                     // @inject_tag: xorm:"bigint comment('创建时间')"
	Platform   Platform  `protobuf:"varint,9,opt,name=platform,proto3,enum=myplay.Platform" json:"platform,omitempty" xorm:"int index comment('注册平台')"`                      // @inject_tag: xorm:"int index comment('注册平台')"
	LoginType  LoginType `protobuf:"varint,10,opt,name=login_type,json=loginType,proto3,enum=myplay.LoginType" json:"login_type,omitempty" xorm:"int index comment('登录类型')"` // @inject_tag: xorm:"int index comment('登录类型')"
}

func (x *AccountData) Reset() {
	*x = AccountData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountData) ProtoMessage() {}

func (x *AccountData) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountData.ProtoReflect.Descriptor instead.
func (*AccountData) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{1}
}

func (x *AccountData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccountData) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AccountData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AccountData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AccountData) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *AccountData) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AccountData) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PlatformTypeNone
}

func (x *AccountData) GetLoginType() LoginType {
	if x != nil {
		return x.LoginType
	}
	return LoginType_LoginTypeNone
}

// 玩家游戏数据
type PlayerData struct {
	state         protoimpl.MessageState `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`

	Id      uint64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" xorm:"bigint autoincr pk"`           // @inject_tag: xorm:"bigint autoincr pk"
	Uid     uint64          `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty" xorm:"bigint index notnull comment('玩家ID')"`         // @inject_tag: xorm:"bigint index notnull comment('玩家ID')"
	Version uint64          `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty" xorm:"version"` // @inject_tag: xorm:"version"
	Base    *PlayerBaseData `protobuf:"bytes,4,opt,name=base,proto3" json:"base,omitempty" xorm:"blob comment('玩家信息')"`        // @inject_tag: xorm:"blob comment('玩家信息')"
	Bag     *PlayerBagData  `protobuf:"bytes,5,opt,name=bag,proto3" json:"bag,omitempty" xorm:"blob comment('背包系统')"`          // @inject_tag: xorm:"blob comment('背包系统')"
}

func (x *PlayerData) Reset() {
	*x = PlayerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerData) ProtoMessage() {}

func (x *PlayerData) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerData.ProtoReflect.Descriptor instead.
func (*PlayerData) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerData) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerData) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PlayerData) GetBase() *PlayerBaseData {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PlayerData) GetBag() *PlayerBagData {
	if x != nil {
		return x.Bag
	}
	return nil
}

type PlayerBaseData struct {
	state         protoimpl.MessageState `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *PlayerBaseData) Reset() {
	*x = PlayerBaseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBaseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBaseData) ProtoMessage() {}

func (x *PlayerBaseData) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBaseData.ProtoReflect.Descriptor instead.
func (*PlayerBaseData) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerBaseData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerBaseData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PlayerBaseData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PlayerBagData struct {
	state         protoimpl.MessageState `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`

	Items []*ItemData `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *PlayerBagData) Reset() {
	*x = PlayerBagData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBagData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBagData) ProtoMessage() {}

func (x *PlayerBagData) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBagData.ProtoReflect.Descriptor instead.
func (*PlayerBagData) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerBagData) GetItems() []*ItemData {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemData struct {
	state         protoimpl.MessageState `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`

	PropId uint32 `protobuf:"varint,1,opt,name=prop_id,json=propId,proto3" json:"prop_id,omitempty"`
	Count  int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ItemData) Reset() {
	*x = ItemData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_database_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemData) ProtoMessage() {}

func (x *ItemData) ProtoReflect() protoreflect.Message {
	mi := &file_database_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemData.ProtoReflect.Descriptor instead.
func (*ItemData) Descriptor() ([]byte, []int) {
	return file_database_proto_rawDescGZIP(), []int{5}
}

func (x *ItemData) GetPropId() uint32 {
	if x != nil {
		return x.PropId
	}
	return 0
}

func (x *ItemData) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_database_proto protoreflect.FileDescriptor

var file_database_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x6d, 0x79, 0x70, 0x6c, 0x61, 0x79, 0x1a, 0x0e, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x67,
	0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x6d, 0x79, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0xab, 0x02,
	0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x6d, 0x79, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x30, 0x0a, 0x0a, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x6d, 0x79, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x0a,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x79, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x12, 0x27, 0x0a, 0x03, 0x62, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6d, 0x79, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42,
	0x61, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x03, 0x62, 0x61, 0x67, 0x22, 0x50, 0x0a, 0x0e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x37, 0x0a,
	0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x26,
	0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6d, 0x79, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x39, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2a, 0x23, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x41, 0x53, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x42, 0x41, 0x47, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_database_proto_rawDescOnce sync.Once
	file_database_proto_rawDescData = file_database_proto_rawDesc
)

func file_database_proto_rawDescGZIP() []byte {
	file_database_proto_rawDescOnce.Do(func() {
		file_database_proto_rawDescData = protoimpl.X.CompressGZIP(file_database_proto_rawDescData)
	})
	return file_database_proto_rawDescData
}

var file_database_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_database_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_database_proto_goTypes = []interface{}{
	(PlayerDataType)(0),    // 0: myplay.PlayerDataType
	(*SessionData)(nil),    // 1: myplay.SessionData
	(*AccountData)(nil),    // 2: myplay.AccountData
	(*PlayerData)(nil),     // 3: myplay.PlayerData
	(*PlayerBaseData)(nil), // 4: myplay.PlayerBaseData
	(*PlayerBagData)(nil),  // 5: myplay.PlayerBagData
	(*ItemData)(nil),       // 6: myplay.ItemData
	(Platform)(0),          // 7: myplay.Platform
	(LoginType)(0),         // 8: myplay.LoginType
}
var file_database_proto_depIdxs = []int32{
	7, // 0: myplay.SessionData.platform:type_name -> myplay.Platform
	7, // 1: myplay.AccountData.platform:type_name -> myplay.Platform
	8, // 2: myplay.AccountData.login_type:type_name -> myplay.LoginType
	4, // 3: myplay.PlayerData.base:type_name -> myplay.PlayerBaseData
	5, // 4: myplay.PlayerData.bag:type_name -> myplay.PlayerBagData
	6, // 5: myplay.PlayerBagData.Items:type_name -> myplay.ItemData
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_database_proto_init() }
func file_database_proto_init() {
	if File_database_proto != nil {
		return
	}
	file_enum_gen_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_database_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBaseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBagData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_database_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_database_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_database_proto_goTypes,
		DependencyIndexes: file_database_proto_depIdxs,
		EnumInfos:         file_database_proto_enumTypes,
		MessageInfos:      file_database_proto_msgTypes,
	}.Build()
	File_database_proto = out.File
	file_database_proto_rawDesc = nil
	file_database_proto_goTypes = nil
	file_database_proto_depIdxs = nil
}
