// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.30.0
// source: enum.gen.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginType int32

const (
	LoginType_LoginTypeNone LoginType = 0 // 登录类型-空
	LoginType_Guest         LoginType = 1 // 登录类型-游客登录
	LoginType_Account       LoginType = 2 // 登录类型-账号
	LoginType_Apple         LoginType = 3 // 登录类型-苹果
	LoginType_Google        LoginType = 4 // 登录类型-谷歌
)

// Enum value maps for LoginType.
var (
	LoginType_name = map[int32]string{
		0: "LoginTypeNone",
		1: "Guest",
		2: "Account",
		3: "Apple",
		4: "Google",
	}
	LoginType_value = map[string]int32{
		"LoginTypeNone": 0,
		"Guest":         1,
		"Account":       2,
		"Apple":         3,
		"Google":        4,
	}
)

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}

func (x LoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[0].Descriptor()
}

func (LoginType) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[0]
}

func (x LoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginType.Descriptor instead.
func (LoginType) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{0}
}

type NodeType int32

const (
	NodeType_Client NodeType = 0 // 节点类型-Client
	NodeType_Gate   NodeType = 1 // 节点类型-Gate
	NodeType_Auth   NodeType = 2 // 节点类型-Auth
	NodeType_Db     NodeType = 3 // 节点类型-Db
	NodeType_Game   NodeType = 4 // 节点类型-Game
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "Client",
		1: "Gate",
		2: "Auth",
		3: "Db",
		4: "Game",
	}
	NodeType_value = map[string]int32{
		"Client": 0,
		"Gate":   1,
		"Auth":   2,
		"Db":     3,
		"Game":   4,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[1].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[1]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{1}
}

type Platform int32

const (
	Platform_PlatformTypeNone Platform = 0 // 平台类型-空
	Platform_Mobile           Platform = 1 // 平台类型-Mobile
	Platform_Desktop          Platform = 2 // 平台类型-Desktop
	Platform_Web              Platform = 3 // 平台类型-Web
	Platform_Ios              Platform = 4 // 平台类型-Ios
	Platform_Android          Platform = 5 // 平台类型-Android
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PlatformTypeNone",
		1: "Mobile",
		2: "Desktop",
		3: "Web",
		4: "Ios",
		5: "Android",
	}
	Platform_value = map[string]int32{
		"PlatformTypeNone": 0,
		"Mobile":           1,
		"Desktop":          2,
		"Web":              3,
		"Ios":              4,
		"Android":          5,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_gen_proto_enumTypes[2].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_enum_gen_proto_enumTypes[2]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_enum_gen_proto_rawDescGZIP(), []int{2}
}

var File_enum_gen_proto protoreflect.FileDescriptor

var file_enum_gen_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x6d, 0x79, 0x70, 0x6c, 0x61, 0x79, 0x2a, 0x4d, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x75, 0x65, 0x73,
	0x74, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x47,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x10, 0x04, 0x2a, 0x3c, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x47, 0x61, 0x74, 0x65, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x75, 0x74,
	0x68, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x44, 0x62, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x47,
	0x61, 0x6d, 0x65, 0x10, 0x04, 0x2a, 0x58, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x10, 0x02,
	0x12, 0x07, 0x0a, 0x03, 0x57, 0x65, 0x62, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x6f, 0x73,
	0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x10, 0x05, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_enum_gen_proto_rawDescOnce sync.Once
	file_enum_gen_proto_rawDescData = file_enum_gen_proto_rawDesc
)

func file_enum_gen_proto_rawDescGZIP() []byte {
	file_enum_gen_proto_rawDescOnce.Do(func() {
		file_enum_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_gen_proto_rawDescData)
	})
	return file_enum_gen_proto_rawDescData
}

var file_enum_gen_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_enum_gen_proto_goTypes = []interface{}{
	(LoginType)(0), // 0: myplay.LoginType
	(NodeType)(0),  // 1: myplay.NodeType
	(Platform)(0),  // 2: myplay.Platform
}
var file_enum_gen_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_gen_proto_init() }
func file_enum_gen_proto_init() {
	if File_enum_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_gen_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_gen_proto_goTypes,
		DependencyIndexes: file_enum_gen_proto_depIdxs,
		EnumInfos:         file_enum_gen_proto_enumTypes,
	}.Build()
	File_enum_gen_proto = out.File
	file_enum_gen_proto_rawDesc = nil
	file_enum_gen_proto_goTypes = nil
	file_enum_gen_proto_depIdxs = nil
}
