// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: table.gen.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalConfig struct {
	state         protoimpl.MessageState `xorm:"-"` 
	UidBeginValue uint64                 `protobuf:"varint,1,opt,name=UidBeginValue,proto3" json:"UidBeginValue,omitempty"` // uid开始值
	GateUrl       string                 `protobuf:"bytes,2,opt,name=GateUrl,proto3" json:"GateUrl,omitempty"`              // 游戏url地址
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GlobalConfig) Reset() {
	*x = GlobalConfig{}
	mi := &file_table_gen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfig) ProtoMessage() {}

func (x *GlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalConfig.ProtoReflect.Descriptor instead.
func (*GlobalConfig) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalConfig) GetUidBeginValue() uint64 {
	if x != nil {
		return x.UidBeginValue
	}
	return 0
}

func (x *GlobalConfig) GetGateUrl() string {
	if x != nil {
		return x.GateUrl
	}
	return ""
}

type GlobalConfigAry struct {
	state         protoimpl.MessageState `xorm:"-"` 
	Ary           []*GlobalConfig        `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields `xorm:"-"`
	sizeCache     protoimpl.SizeCache `xorm:"-"`
}

func (x *GlobalConfigAry) Reset() {
	*x = GlobalConfigAry{}
	mi := &file_table_gen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfigAry) ProtoMessage() {}

func (x *GlobalConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_table_gen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalConfigAry.ProtoReflect.Descriptor instead.
func (*GlobalConfigAry) Descriptor() ([]byte, []int) {
	return file_table_gen_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalConfigAry) GetAry() []*GlobalConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

var File_table_gen_proto protoreflect.FileDescriptor

var file_table_gen_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x6d, 0x79, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x4e, 0x0a, 0x0c, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x55, 0x69, 0x64,
	0x42, 0x65, 0x67, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0d, 0x55, 0x69, 0x64, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x47, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x47, 0x61, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x39, 0x0a, 0x0f, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x72, 0x79, 0x12, 0x26, 0x0a, 0x03,
	0x41, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x79, 0x70, 0x6c,
	0x61, 0x79, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x03, 0x41, 0x72, 0x79, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_table_gen_proto_rawDescOnce sync.Once
	file_table_gen_proto_rawDescData []byte
)

func file_table_gen_proto_rawDescGZIP() []byte {
	file_table_gen_proto_rawDescOnce.Do(func() {
		file_table_gen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_table_gen_proto_rawDesc), len(file_table_gen_proto_rawDesc)))
	})
	return file_table_gen_proto_rawDescData
}

var file_table_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_table_gen_proto_goTypes = []any{
	(*GlobalConfig)(nil),    // 0: myplay.GlobalConfig
	(*GlobalConfigAry)(nil), // 1: myplay.GlobalConfigAry
}
var file_table_gen_proto_depIdxs = []int32{
	0, // 0: myplay.GlobalConfigAry.Ary:type_name -> myplay.GlobalConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_table_gen_proto_init() }
func file_table_gen_proto_init() {
	if File_table_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_table_gen_proto_rawDesc), len(file_table_gen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_table_gen_proto_goTypes,
		DependencyIndexes: file_table_gen_proto_depIdxs,
		MessageInfos:      file_table_gen_proto_msgTypes,
	}.Build()
	File_table_gen_proto = out.File
	file_table_gen_proto_goTypes = nil
	file_table_gen_proto_depIdxs = nil
}
